### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-decals#2]
Just to clarify this adds a texture on top of the normal block texture? It does not change the texture of the block itself? or set it for that matter

**Comment by deathcap** [comment]
Right, voxel-decals adds a new mesh for a textured plane on a given block face. The decal can be removed, changed, added, without affecting the underlying block textures.

Currently it is only used by [voxel-mine](https://github.com/voxel/voxel-mine) to provide the mining damage progress overlay, but the module is generic enough so it could be used for other purposes (haven't found any, but ideas welcome :p)
